# Generated by Django 5.1.2 on 2025-01-03 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_sending",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало рассылки"
                    ),
                ),
                (
                    "end_sending",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("создана", "создана"),
                            ("запущена", "запущена"),
                            ("завершена", "завершена"),
                        ],
                        default="создана",
                        help_text="Выберите статус рассылки",
                        max_length=100,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status", "message"],
                "permissions": [("can_finish_mailing", "can finish mailing")],
            },
        ),
        migrations.CreateModel(
            name="Mailing_Attempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату и время попытки",
                        verbose_name="Дата попытки",
                    ),
                ),
                (
                    "attempt_status",
                    models.CharField(
                        choices=[("успешно", "успешно"), ("неуспешно", "неуспешно")],
                        default="успешно",
                        help_text="Введите статус",
                        max_length=100,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ сервера почты",
                        null=True,
                        verbose_name="Ответ сервера почты",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите рассылку для попытки",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["attempt_date", "attempt_status", "mailing"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Введите тему сообщения",
                        max_length=100,
                        verbose_name="Тема сообщения",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст сообщения",
                        verbose_name="Текст сообщения",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["topic"],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите сообщение для рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес электронной почты получателя",
                        max_length=254,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=250, verbose_name="Имя получателя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=250, verbose_name="Фамилия получателя"),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Отчество получателя",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальное имя формируется из фамилии и имени",
                        max_length=255,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email", "first_name", "last_name"],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Выберите получателей для рассылки",
                to="mailing.recipient",
                verbose_name="Получатели",
            ),
        ),
    ]
